site_name: marianne
site_url: https://psice.github.io/marianne

nav:
  - Home: index.md
  - Slides:
    - Overview: slides/overview.md

theme:
  name: material
  custom_dir: theme
  palette:
    primary: black
    accent: red
  feature:
    tabs: true

reveal:
  path: reveal.js
  transition: slide
  theme:
    name: moon.css
    path: theme
  plugin:
    path: reveal.js/plugin

extra:
  author:
    name: psiace
